# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
  - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Setting SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Scan public keys
      run: ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts
    - name: Connect to Server
      uses: actions/setup-ssh@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
    - name: Run Command
      uses: tiyee/action-ssh@v1.0.1
      with:
        # Command to execute on the remote server.
          command: ls
          # Hostname or IP address of the server.
          host: ${{ secrets.HOST }}
          # Username for authentication.
          username: ${{ secrets.USERNAME }}
          # Port number of the server.
          port: ${{ secrets.PORT }}
          # File  string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          privateKey: ${{ secrets.SSH_KEY }}
          
      # run: |
      #     ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "whoami;ls -la"
          
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: SSH into remote server and run command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: s3.serv00.com
    #     username: ${{ secrets.USERNAME }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     script: |
    #       whoami
    #       cd cd /home/fuhj/repo/gost
    #       ls -l

    # - name: SSH into remote server and run command
    #   uses: appleboy/ssh-action@master
    #   with:
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.USERNAME }}
    #       password: ${{ secrets.PASSWORD }}
    #       port: ${{ secrets.PORT }}
    #       script: whoami
          # |
          #   cd /home/fuhj/repo/gost
          #   ls -l
          #   ps -ef|grep gost
